products:

- name: Roses
  code: R12
  bundles:
  - quantity:   5
    price:      699
  - quantity:   10
    price:      1299

- name: Lilies
  code: L09
  bundles:
  - quantity:   3
    price:      995
  - quantity:   6
    price:      1695
  - quantity:   9
    price:      2495

- name: Tulips
  code: T58
  bundles:
  - quantity:   3
    price:      595
  - quantity:   5
    price:      995
  - quantity:   9
    price:      1699

